from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any


# ---------------------------------------------------------
# NORMALIZATION
# ---------------------------------------------------------

DEVANAGARI_DIGITS = str.maketrans(
    "०१२३४५६७८९",
    "0123456789",
)

ARABIC_INDIC_DIGITS = str.maketrans(
    "٠١٢٣٤٥٦٧٨٩",
    "0123456789",
)


def normalize_digits(text: str) -> str:
    text = text.translate(DEVANAGARI_DIGITS)
    text = text.translate(ARABIC_INDIC_DIGITS)
    return text


def clean_text(text: str) -> str:
    if not text:
        return ""

    text = normalize_digits(text)

    # Remove obvious Surya-generated HTML/image descriptions.
    text = re.sub(r"<img[^>]*>", " ", text, flags=re.I)
    text = re.sub(r"<[^>]+>", " ", text)

    # Remove obvious garbage generated by VLM.
    garbage = [
        "second session",
        "state of the united states",
        "state of massachusetts",
        "see also",
        "section iii",
        "black and white photograph",
        "black and white image",
        "person in a suit",
        "community council",
    ]

    lowered = text.lower()
    for item in garbage:
        lowered = lowered.replace(item, " ")

    # Keep Hindi/English/numbers/basic punctuation.
    text = re.sub(
        r"[^\w\s\u0900-\u097F\u0980-\u09FF./()\-:,₹]",
        " ",
        text,
        flags=re.UNICODE,
    )

    text = re.sub(r"\s+", " ", text).strip()

    return text


# ---------------------------------------------------------
# OCR QUALITY
# ---------------------------------------------------------

def line_confidence(line: dict[str, Any]) -> float:
    values = []

    for key in ("detector_confidence", "recognition_confidence"):
        value = line.get(key)
        if isinstance(value, (int, float)):
            values.append(float(value))

    if not values:
        return 0.0

    return sum(values) / len(values)


def cell_confidence(cell: dict[str, Any]) -> float:
    values = []

    detection = cell.get("detection_confidence")
    if isinstance(detection, (int, float)):
        values.append(float(detection))

    for line in cell.get("lines", []):
        confidence = line_confidence(line)
        if confidence:
            values.append(confidence)

    if not values:
        return 0.0

    return sum(values) / len(values)


# ---------------------------------------------------------
# TEXT EXTRACTION
# ---------------------------------------------------------

def get_cell_lines(cell: dict[str, Any]) -> list[dict[str, Any]]:
    result = []

    for line in cell.get("lines", []):
        text = clean_text(line.get("text", ""))

        if not text:
            continue

        result.append(
            {
                "text": text,
                "confidence": round(line_confidence(line), 4),
                "bbox": line.get("bbox"),
            }
        )

    return result


def get_cell_text(cell: dict[str, Any]) -> str:
    lines = get_cell_lines(cell)

    if lines:
        return "\n".join(item["text"] for item in lines)

    return clean_text(cell.get("text", ""))


# ---------------------------------------------------------
# NUMERIC CANDIDATES
# ---------------------------------------------------------

NUMBER_PATTERN = re.compile(
    r"""
    (?<!\w)
    \d+(?:[./-]\d+)*
    (?!\w)
    """,
    re.VERBOSE,
)


def numeric_candidates(text: str) -> list[str]:
    text = normalize_digits(text)

    values = NUMBER_PATTERN.findall(text)

    # Remove obvious page/column artifacts.
    filtered = []

    for value in values:
        if value in {"1", "2", "3", "4", "5", "6",
                     "7", "8", "9", "10", "11", "12"}:
            continue

        filtered.append(value)

    return filtered


# ---------------------------------------------------------
# KEYWORD DETECTION
# ---------------------------------------------------------

OWNER_KEYWORDS = [
    "स्वामी",
    "भूमि स्वामी",
    "भूस्वामी",
    "बूमिस्वामी",
    "खातेदार",
    "अभानसिंह",
    "हजारी",
    "लाल",
    "सिंह",
]

LAND_KEYWORDS = [
    "भूमि",
    "भू",
    "कृषि",
    "आवासीय",
    "सिंचित",
    "असिंचित",
    "रकबा",
    "क्षेत्रफल",
]

MUTATION_KEYWORDS = [
    "नामांतरण",
    "नामान्तरण",
    "परिवर्तन",
    "आदेश",
    "प्रकरण",
    "तारीख",
    "दिनांक",
]

REGISTRATION_KEYWORDS = [
    "पंजी",
    "पंजीयन",
    "रजिस्ट्री",
    "रजिस्ट्रेशन",
    "विक्रय",
    "बिक्री",
    "पंजीकरण",
]


def contains_any(text: str, keywords: list[str]) -> bool:
    lowered = text.lower()
    return any(keyword.lower() in lowered for keyword in keywords)


# ---------------------------------------------------------
# PAGE / CELL NORMALIZATION
# ---------------------------------------------------------

def prepare_document(document: dict[str, Any]) -> list[dict[str, Any]]:
    prepared = []

    for page in document.get("pages", []):
        page_number = page.get("page_number")
        result = page.get("result", {})

        for cell in result.get("cells", []):
            text = get_cell_text(cell)

            if not text:
                continue

            bbox = cell.get("bbox", [0, 0, 0, 0])

            x1, y1, x2, y2 = bbox

            prepared.append(
                {
                    "page": page_number,
                    "cell_id": cell.get("cell_id"),
                    "bbox": bbox,
                    "x_center": (x1 + x2) / 2,
                    "y_center": (y1 + y2) / 2,
                    "text": text,
                    "confidence": round(cell_confidence(cell), 4),
                    "numbers": numeric_candidates(text),
                }
            )

    return prepared


# ---------------------------------------------------------
# CANDIDATE OBJECT
# ---------------------------------------------------------

def evidence(
    cell: dict[str, Any],
    reason: str,
    confidence_modifier: float = 1.0,
) -> dict[str, Any]:

    confidence = max(
        0.0,
        min(
            1.0,
            cell["confidence"] * confidence_modifier,
        ),
    )

    return {
        "page": cell["page"],
        "cell_id": cell["cell_id"],
        "value": cell["text"],
        "confidence": round(confidence, 4),
        "reason": reason,
        "bbox": cell["bbox"],
    }


# ---------------------------------------------------------
# OWNER EXTRACTION
# ---------------------------------------------------------

def extract_owner_candidates(cells: list[dict[str, Any]]) -> list[dict[str, Any]]:
    candidates = []

    for cell in cells:
        text = cell["text"]

        if contains_any(text, OWNER_KEYWORDS):
            candidates.append(
                evidence(
                    cell,
                    "Text contains landowner/ownership-related terminology.",
                    0.90,
                )
            )

    return sorted(
        candidates,
        key=lambda item: item["confidence"],
        reverse=True,
    )


# ---------------------------------------------------------
# LAND CLASSIFICATION
# ---------------------------------------------------------

def extract_land_classification(
    cells: list[dict[str, Any]],
) -> list[dict[str, Any]]:

    candidates = []

    for cell in cells:
        text = cell["text"]

        if contains_any(text, LAND_KEYWORDS):
            candidates.append(
                evidence(
                    cell,
                    "Text contains land/use/classification terminology.",
                    0.85,
                )
            )

    return sorted(
        candidates,
        key=lambda item: item["confidence"],
        reverse=True,
    )


# ---------------------------------------------------------
# AREA CANDIDATES
# ---------------------------------------------------------

def extract_area_candidates(
    cells: list[dict[str, Any]],
) -> list[dict[str, Any]]:

    candidates = []

    for cell in cells:
        text = cell["text"]

        # Area-like decimal values.
        decimals = re.findall(
            r"(?<!\w)\d+\.\d+(?!\w)",
            normalize_digits(text),
        )

        for value in decimals:
            candidates.append(
                {
                    "page": cell["page"],
                    "cell_id": cell["cell_id"],
                    "value": value,
                    "source_text": text,
                    "confidence": round(
                        cell["confidence"] * 0.75,
                        4,
                    ),
                    "bbox": cell["bbox"],
                }
            )

    return sorted(
        candidates,
        key=lambda item: item["confidence"],
        reverse=True,
    )


# ---------------------------------------------------------
# KHASRA / SURVEY CANDIDATES
# ---------------------------------------------------------

def extract_number_candidates(
    cells: list[dict[str, Any]],
) -> list[dict[str, Any]]:

    candidates = []

    for cell in cells:
        for value in cell["numbers"]:

            # Ignore tiny OCR artifacts.
            if len(value.replace("-", "").replace("/", "")) < 2:
                continue

            candidates.append(
                {
                    "page": cell["page"],
                    "cell_id": cell["cell_id"],
                    "value": value,
                    "source_text": cell["text"],
                    "confidence": round(
                        cell["confidence"] * 0.70,
                        4,
                    ),
                    "bbox": cell["bbox"],
                }
            )

    return sorted(
        candidates,
        key=lambda item: item["confidence"],
        reverse=True,
    )


# ---------------------------------------------------------
# MUTATION / REGISTRATION
# ---------------------------------------------------------

def extract_mutation_candidates(
    cells: list[dict[str, Any]],
) -> list[dict[str, Any]]:

    candidates = []

    for cell in cells:
        if contains_any(cell["text"], MUTATION_KEYWORDS):
            candidates.append(
                evidence(
                    cell,
                    "Text contains mutation/order terminology.",
                    0.85,
                )
            )

    return candidates


def extract_registration_candidates(
    cells: list[dict[str, Any]],
) -> list[dict[str, Any]]:

    candidates = []

    for cell in cells:
        if contains_any(cell["text"], REGISTRATION_KEYWORDS):
            candidates.append(
                evidence(
                    cell,
                    "Text contains registration-related terminology.",
                    0.85,
                )
            )

    return candidates


# ---------------------------------------------------------
# LOCATION
# ---------------------------------------------------------

def extract_location_from_text(text: str) -> dict[str, Any]:
    """
    Extract the printed header location when it is available.

    Expected examples:
        जिला : भोपाल
        तहसील : कोलार
        गांव : बाग मुंगालिया

    We intentionally keep current and record location separate.
    """

    result = {
        "district": None,
        "tehsil": None,
        "village": None,
    }

    if not text:
        return result

    district = re.search(
        r"जिला\s*[:\-]\s*([^,\n]+)",
        text,
    )

    tehsil = re.search(
        r"तहसील\s*[:\-]\s*([^,\n]+)",
        text,
    )

    village = re.search(
        r"(?:गांव|गाँव|ग्राम)\s*[:\-]\s*([^,\n]+)",
        text,
    )

    if district:
        result["district"] = district.group(1).strip()

    if tehsil:
        result["tehsil"] = tehsil.group(1).strip()

    if village:
        result["village"] = village.group(1).strip()

    return result


# ---------------------------------------------------------
# FINAL DOCUMENT EXTRACTION
# ---------------------------------------------------------

def extract_land_record_fields(
    document: dict[str, Any],
    pdf_text: str = "",
) -> dict[str, Any]:

    cells = prepare_document(document)

    owners = extract_owner_candidates(cells)
    classifications = extract_land_classification(cells)
    areas = extract_area_candidates(cells)
    numbers = extract_number_candidates(cells)

    mutations = extract_mutation_candidates(cells)
    registrations = extract_registration_candidates(cells)

    location = extract_location_from_text(pdf_text)

    # We deliberately do NOT choose a khasra/survey number
    # from arbitrary numeric OCR yet.
    #
    # Instead expose candidates for the next geometry-aware stage.

    return {
        "schema_version": "2.0",

        "location": {
            "current_location": location,
            "record_location": {
                "district": None,
                "tehsil": None,
                "village": None,
            },
        },

        "land_records": [
            {
                "landowner_details": owners,
                "survey_number": None,
                "khasra_number": None,
                "khata_number": None,
                "plot_area": None,
                "land_classification": (
                    classifications[0]
                    if classifications
                    else None
                ),
                "ownership_details": owners,
            }
        ],

        "mutation_records": mutations,

        "registration_information": registrations,

        "candidates": {
            "numeric_values": numbers,
            "area_values": areas,
            "owner_values": owners,
            "classification_values": classifications,
        },

        "raw_evidence": cells,

        "quality": {
            "pages_processed": len(document.get("pages", [])),
            "cells_with_text": len(cells),
            "owner_candidates": len(owners),
            "area_candidates": len(areas),
            "numeric_candidates": len(numbers),
            "mutation_candidates": len(mutations),
            "registration_candidates": len(registrations),
        },
    }


# ---------------------------------------------------------
# CLI
# ---------------------------------------------------------

if __name__ == "__main__":

    import argparse

    parser = argparse.ArgumentParser()

    parser.add_argument(
        "--input",
        required=True,
        help="Path to document_result.json",
    )

    parser.add_argument(
        "--output",
        required=True,
        help="Path for structured JSON",
    )

    parser.add_argument(
        "--pdf-text",
        default="",
        help="Optional extracted PDF text",
    )

    args = parser.parse_args()

    input_path = Path(args.input)
    output_path = Path(args.output)

    with input_path.open(
        "r",
        encoding="utf-8",
    ) as f:
        document = json.load(f)

    result = extract_land_record_fields(
        document,
        pdf_text=args.pdf_text,
    )

    output_path.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    with output_path.open(
        "w",
        encoding="utf-8",
    ) as f:
        json.dump(
            result,
            f,
            ensure_ascii=False,
            indent=2,
        )

    print("=" * 70)
    print("DOCUMENT FIELD EXTRACTION COMPLETE")
    print("=" * 70)
    print(f"Input : {input_path}")
    print(f"Output: {output_path}")
    print()
    print(json.dumps(
        result["quality"],
        ensure_ascii=False,
        indent=2,
    ))