from pathlib import Path
import json
from statistics import median


# ============================================================
# PATHS
# ============================================================

PROJECT_ROOT = Path.cwd()

INPUT = (
    PROJECT_ROOT
    / "outputs"
    / "documents"
    / "pdf1"
    / "document_result.json"
)

OUTPUT = (
    PROJECT_ROOT
    / "outputs"
    / "documents"
    / "pdf1"
    / "reconstructed_records.json"
)


# ============================================================
# BASIC HELPERS
# ============================================================

def cell_center(cell):
    x1, y1, x2, y2 = cell["bbox"]
    return (
        (x1 + x2) / 2,
        (y1 + y2) / 2,
    )


def cell_width(cell):
    x1, _, x2, _ = cell["bbox"]
    return x2 - x1


def clean_text(text):
    if not text:
        return ""

    text = str(text)

    # Remove obvious HTML fragments generated by OCR
    import re

    text = re.sub(r"<[^>]+>", " ", text)
    text = re.sub(r"\s+", " ", text)

    return text.strip()


# ============================================================
# ROW RECONSTRUCTION
# ============================================================

def build_rows(cells, y_tolerance=70):
    """
    Group cells belonging to the same physical table row.

    We use the vertical center of each detected cell.
    """

    valid = []

    for cell in cells:
        if not cell.get("bbox"):
            continue

        _, yc = cell_center(cell)

        valid.append(
            {
                "cell": cell,
                "yc": yc,
            }
        )

    valid.sort(key=lambda item: item["yc"])

    rows = []

    for item in valid:
        cell = item["cell"]
        yc = item["yc"]

        placed = False

        for row in rows:
            if abs(yc - row["y_center"]) <= y_tolerance:
                row["cells"].append(cell)

                # Update row center
                row["y_center"] = median(
                    [cell_center(c)[1] for c in row["cells"]]
                )

                placed = True
                break

        if not placed:
            rows.append(
                {
                    "y_center": yc,
                    "cells": [cell],
                }
            )

    # Sort cells left → right
    for row in rows:
        row["cells"].sort(
            key=lambda c: cell_center(c)[0]
        )

    return rows


# ============================================================
# PAGE 2 — KHASRA TABLE
# ============================================================

def classify_page2_column(cell):
    """
    Page 2 is the main P. II Khasra Panch table.

    Based on the actual rendered table:

        (1) serial number
        (2) area
        (3) landowner / account-holder details
        (4) previous/related owner information
        (5) crop name
        (6) crop area

    The remaining columns are currently mostly empty.
    """

    xc, _ = cell_center(cell)

    # --------------------------------------------------------
    # Column (1)
    # क्रमांक
    # --------------------------------------------------------
    if 70 <= xc < 175:
        return "serial_number"

    # --------------------------------------------------------
    # Column (2)
    # क्षेत्रफल
    # --------------------------------------------------------
    if 175 <= xc < 255:
        return "plot_area"

    # --------------------------------------------------------
    # Column (3)
    # खातेदार / भूमिस्वामी विवरण
    # --------------------------------------------------------
    if 255 <= xc < 500:
        return "landowner_details"

    # --------------------------------------------------------
    # Column (4)
    # previous/related owner information
    # --------------------------------------------------------
    if 500 <= xc < 630:
        return "related_owner_details"

    # --------------------------------------------------------
    # Column (5)
    # फसल का नाम
    # --------------------------------------------------------
    if 630 <= xc < 720:
        return "crop_name"

    # --------------------------------------------------------
    # Column (6)
    # क्षेत्रफल
    # --------------------------------------------------------
    if 720 <= xc < 810:
        return "crop_area"

    # --------------------------------------------------------
    # Remaining columns
    # --------------------------------------------------------
    if 810 <= xc < 900:
        return "other"

    return None


def reconstruct_page2(cells):
    """
    Reconstruct the actual land records from page 2.

    Footer/extra handwritten marks near the bottom are ignored.
    """

    rows = build_rows(cells, y_tolerance=70)

    records = []

    for row_index, row in enumerate(rows, start=1):

        # The actual table data in this document occupies
        # the first five meaningful rows.
        #
        # Rows below this are footer/extra handwriting and
        # should not become land records.
        if row["y_center"] > 1700:
            continue

        record = {
            "row_number": row_index,
            "serial_number": None,
            "plot_area": None,
            "landowner_details": None,
            "related_owner_details": None,
            "crop_name": None,
            "crop_area": None,
            "other": None,
            "raw_cells": [],
        }

        for cell in row["cells"]:

            column = classify_page2_column(cell)

            text = clean_text(cell.get("text", ""))

            raw_cell = {
                "cell_id": cell.get("cell_id"),
                "bbox": cell.get("bbox"),
                "column": column,
                "text": text,
                "detection_confidence": cell.get(
                    "detection_confidence"
                ),
                "num_lines": cell.get("num_lines", 0),
            }

            record["raw_cells"].append(raw_cell)

            if not column:
                continue

            # Empty OCR should not overwrite useful data
            if not text:
                continue

            # If multiple cells land in the same logical column,
            # preserve all text instead of throwing anything away.
            if record[column] is None:
                record[column] = text
            else:
                record[column] += " | " + text

        # Only retain rows containing actual handwritten content
        meaningful_fields = [
            "serial_number",
            "plot_area",
            "landowner_details",
            "crop_name",
            "crop_area",
        ]

        if any(record[field] for field in meaningful_fields):
            records.append(record)

    return records


# ============================================================
# PAGE 1 — CONTINUATION TABLE
# ============================================================

def classify_page1_column(cell):
    """
    Page 1 is NOT the main Khasra table.

    It is the continuation/change section containing columns
    approximately 13–20.

    We therefore preserve its columns as continuation data
    rather than pretending that the numbers are khasra/khata
    numbers.
    """

    xc, _ = cell_center(cell)

    if xc < 160:
        return "column_13"

    if xc < 335:
        return "column_14"

    if xc < 470:
        return "column_15"

    if xc < 560:
        return "column_16"

    if xc < 650:
        return "column_17"

    if xc < 780:
        return "column_18"

    if xc < 810:
        return "column_19"

    if xc < 950:
        return "column_20"

    return None


def reconstruct_page1(cells):
    """
    Preserve page-1 continuation information.

    No semantic land-record fields are inferred here.
    """

    rows = build_rows(cells, y_tolerance=70)

    continuation_rows = []

    for row_index, row in enumerate(rows, start=1):

        record = {
            "row_number": row_index,
            "columns": {},
            "raw_cells": [],
        }

        for cell in row["cells"]:

            column = classify_page1_column(cell)
            text = clean_text(cell.get("text", ""))

            record["raw_cells"].append(
                {
                    "cell_id": cell.get("cell_id"),
                    "bbox": cell.get("bbox"),
                    "column": column,
                    "text": text,
                    "detection_confidence": cell.get(
                        "detection_confidence"
                    ),
                    "num_lines": cell.get("num_lines", 0),
                }
            )

            if not column or not text:
                continue

            if column not in record["columns"]:
                record["columns"][column] = text
            else:
                record["columns"][column] += " | " + text

        if record["columns"]:
            continuation_rows.append(record)

    return continuation_rows


# ============================================================
# DOCUMENT RECONSTRUCTION
# ============================================================

def reconstruct_document(data):
    pages = data.get("pages", [])

    page2_records = []
    page1_continuation = []

    page_summaries = []

    for page in pages:

        page_number = page.get("page_number")

        result = page.get("result", {})
        cells = result.get("cells", [])

        if page_number == 2:
            records = reconstruct_page2(cells)
            page2_records.extend(records)

            page_summaries.append(
                {
                    "page_number": page_number,
                    "type": "khasra_main_table",
                    "num_cells": len(cells),
                    "num_records": len(records),
                }
            )

        elif page_number == 1:
            continuation = reconstruct_page1(cells)
            page1_continuation.extend(continuation)

            page_summaries.append(
                {
                    "page_number": page_number,
                    "type": "continuation_columns_13_20",
                    "num_cells": len(cells),
                    "num_rows": len(continuation),
                }
            )

        else:
            page_summaries.append(
                {
                    "page_number": page_number,
                    "type": "unknown",
                    "num_cells": len(cells),
                }
            )

    return {
        "status": "success",

        "document": data.get("document", {}),

        "page_summaries": page_summaries,

        # MAIN STRUCTURED RECORDS
        "land_records": page2_records,

        # PRESERVED PAGE-1 INFORMATION
        "continuation": page1_continuation,
    }


# ============================================================
# MAIN
# ============================================================

def main():

    if not INPUT.exists():
        raise FileNotFoundError(
            f"Input file not found: {INPUT}"
        )

    with INPUT.open(
        "r",
        encoding="utf-8"
    ) as f:
        data = json.load(f)

    reconstructed = reconstruct_document(data)

    OUTPUT.parent.mkdir(
        parents=True,
        exist_ok=True
    )

    with OUTPUT.open(
        "w",
        encoding="utf-8"
    ) as f:
        json.dump(
            reconstructed,
            f,
            ensure_ascii=False,
            indent=2
        )

    print()
    print("=" * 60)
    print("TABLE RECONSTRUCTION COMPLETE")
    print("=" * 60)
    print()

    print(
        f"Land records: "
        f"{len(reconstructed['land_records'])}"
    )

    print(
        f"Continuation rows: "
        f"{len(reconstructed['continuation'])}"
    )

    print()

    for record in reconstructed["land_records"]:

        print(
            f"ROW {record['row_number']}:"
        )

        print(
            "  serial:",
            record["serial_number"]
        )

        print(
            "  area:",
            record["plot_area"]
        )

        print(
            "  owner:",
            record["landowner_details"]
        )

        print(
            "  crop:",
            record["crop_name"]
        )

        print(
            "  crop area:",
            record["crop_area"]
        )

        print()

    print(
        f"Output: {OUTPUT}"
    )


if __name__ == "__main__":
    main()